# Generated by Django 2.2 on 2020-05-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200523_1627'),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='survey',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='option',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
